---
Name: siteinfo
After:
  - 'mysite/*'
---
# YAML configuration for SilverStripe
# See http://doc.silverstripe.org/framework/en/topics/configuration
# Caution: Indentation through two spaces, not tabs
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - SixF\SiteInfo\Extension\SiteInfo

SixF\\SiteInfo\Page_Controller:
  extensions:
    - SixF\SiteInfo\Extension\SiteInfoController
